env:
  global:
    - secure: HsMO2npi6oePcBK6F4CDn4ZpfH2kZECXKMALN5mVTRtekfgCBrOZVsXQP5SfhGOW5cvseOnmr0ESrQ/6kqVRKAONn8YCRAQwYfmAe+T0YsCVDQtuEU03Ec9SruLY/EVpsWP7ezsQO5koen9KpBLI6rgwpclZi+8Uf6pNZMBf0+G6I6EVCrsBPvWKQRn+JJV0Mh64o8GycDZFH+YQewRPok8ak2U++NST7WDGBW9udIIlFlLnf2k1WPzbwvBCxhPQaxNY7Lo0FrbJCRKAcibKEX906ZMQw6bHMF7LwYB0VozfPjKm7SOxBAlN1HbaUjHzDkio7mPhBCK1js9I7xSKOoAb260qgEQiXRAVI8asUaG2CH5bg2y7lTjuRI2/fHx7op0v3f7Aa9n9irlBrArIcn5EkiiKl7xg540Au6IQh32disuafZSdlKt6g7w8Gj2bFBf7F1Q9chtkpU0AkZN3GtioiY6xcEOHxGErVxbGzSmKSLpp/3aqRR9om5zuLvLqN8kMLGNFfCudfODxf2OC5wIg73JeKlAU8lIevDVDT/5JHoqiR3urhHVkGh4nmr7sVjDk5rmo5e25QssxJV5kqXbjfOLyXw3vZGQ8QXy6AGn/CAXnZZl20GLVqPTgGW55DavfHYLFwWklRq99eItkDN36XgTbVs3z6/ovEIRUnHU=
    - secure: a6Z/zrO6h6i7r32gLSsVzKsc6v93FRjbgeTyIJhBYXy6qxhVR4eWhRaIb+UEadcBJqyg6MvXHPyRkdsxDRdm0ZqdZKmAvQ2x3YgupR8WKF3YpslTxySbteyYfXS3XUymuRRG7Gj97kf7lAWsduxNx13HjEhXGukyFuFCO87THD6BiCYfFUWVFSmGGvBIq82jkkdcRt9y5SDbjvcI9w80zwbWed6tk7+VDOcaVcqnOC2kEnNOG65+KSofeTmYGpVkuegPXyJb5DppvjVDW3a/Htv5jCv//pqGcYJ+yBEXqxT+zDrIcUD52UBzndx013O++uGH4VurL04QVLVUF18SskBCZlOnPFKuLTJH3JqCMb+93X7oeknJgyHd/gF1mG9cm0vbc2qfoC/2uRCdEBgMWHt4VISu4rswyTyG6SMy3pi1Ha+RMi179LWhZpXBJJRMI5yfDJfbGf0fpQAdQHDEYnixMrtbiJ4NV5WvuXBmYLlconnVOFzNyIF5YtRETK1eAg0u3jhFsLDg8kW9WNQAy3sS8NhFgCPlYLDsr2QCoHKuxaQG52xrtTpz2iM4eoae3LCfDE4qQaAZ1rkA2LqBa/t9z623iMXOm0bgFvHSeh98HuLF2qCcPagf9JN2HxMhiTgoIn11ruGiHAVp9f4QrJyhRmJVyXFq/EQ3pZKmsF8=
before_install:
  - curl https://sh.rustup.rs > cargo.sh
  - sh cargo.sh -y
  - source $HOME/.cargo/env
os: linux
dist: bionic
language: node_js
node_js:
  - lts/*
deploy:
  provider: script
  script: bash deploy_scripts/travis_deploy.sh
  on:
    branch: master
