name: deploy
on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: echo "${{ secrets.HOST_KEY }}" > known_hosts
      - run: echo "${{ secrets.USER_SSH_KEY }}" > key_file && chmod 600 key_file
      - run: rsync -av --del -e "ssh -i key_file -o UserKnownHostsFile=known_hosts" dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_NAME }}:${{ secrets.DEPLOY_DIR }}
